---
- hosts: docker
  gather_facts: no
  sudo: yes
  tasks:
  - name: set repoPath
    set_fact:
     repoPath: '/etc/dockermanager'
  - name: install git, python and docker
    apt: pkg={{item}} state=present
    with_items:
     - git
     - python3
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common
     - python3-pip
     - virtualenv
     - python3-setuptools    
  - name: Add Docker GPG apt Key
    apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present
  - name: Add Docker Repository
    apt_repository:
     repo: deb https://download.docker.com/linux/ubuntu bionic stable
     state: present
  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest
  - name: Ensure repo is up-to-date
    git:
     repo: https://github.com/Kreidl/pydockermanager.git
     dest: "{{repoPath}}"
     version: master
     update: yes
  - name: Make install.sh an executable
    file:
      path: "{{repoPath}}/install.sh" 
      mode: '755'
  - name: Make app.py an executable
    file:
      path: "{{repoPath}}/app.py" 
      mode: '755'
  - name: Execute the installscript
    command: sh "{{repoPath}}/install.sh"